import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

// ADDED
import 'bootstrap/dist/css/bootstrap.min.css'
import React, { useState, useEffect } from 'react'
import ArticleList from './components/ArticleList'

export default function Home() {

  const [articles, setArticles] = useState([])

  useEffect( () => {
    fetch('http://127.0.0.1:8000/articles/', {
      'method': 'GET',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Token a1c1842048db2f425c0c11a97d9da373ed13b503'
      }
    })

    .then(resp => resp.json())
    .then(resp => setArticles(resp))
    .catch(error => console.log(error))
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className='container bg-dark text-white'>
          <div style={{textAlign: 'center', padding: '10px'}}>
            <h1>Django & ReactJS</h1>
          </div>

          <div className={styles.container}>
            <ArticleList articlesList = {articles}></ArticleList>
          </div>
        </div>
      </main>
    </>
  )
}
