import Head from 'next/head'
import Image from 'next/image'
import { Inter, Redacted_Script } from 'next/font/google'
import styles from '@/styles/Home.module.css'

// Added
import 'bootstrap/dist/css/bootstrap.min.css'
import { Route, BrowserRouter } from 'react-router-dom'
import React from 'react'

// FUNCTIONAL & CLASS Components
import FuncComponent from './api/components/Props, Event, Functional_funcComponent'
import ClassComponent from './api/components/Props, Event_Class_classComponent'
import NameClassComp from './api/components/States_Name'
import Example from './api/components/Mapping_Example'
import Example2 from './api/components/Mapping_Example2'
import Form from './api/components/Forms & Life Cycle Methods_Form'
import MyFragment from './api/components/React Fragment_MyFragment'
import ContextAPI_ComponentA from './api/components/ContextAPI_ComponentA'
import ContextAPI_ComponentB from './api/components/ContextAPI_ComponentB'
import Hooks_Counter from './api/components/Hooks_Counter'
import Hooks_CounterHooks from './api/components/Hooks_useEffect_CounterHooks'
import FetchData from './api/components/Hooks _useState & useEffect_FetchData'
import ComponentA from './api/components/Hooks_useContext_ComponentA'
import Reducer from './api/components/Hooks_useReducer_Reducer'
import FetchDataReducer from './api/components/Hooks_useReducer & useEffect_FetchData'

const inter = Inter({ subsets: ['latin'] })

export const MyContext = React.createContext()

function Router() {
  return(
    <BrowserRouter>
      {/*
        <Route exact path = '/' component = { App }/>
      */}
      <Route exact path = '/login' component = { Form }/>
    </BrowserRouter>
  );
}

/*
ReactDOM.render(
  <React.StrictMode>
    <Router />
  </React.StrictMode>

  document.getElementById('root')
);
*/

export default function Home() {

  function ClickMe() {
    alert('CLASS Clicked.')
  }

  return (
    <>
    
      <div className='container'>
        {/*
        <FuncComponent fname = "Bryan" lname = "Pintor"></FuncComponent>
        <ClassComponent uname = "bossing" myclick = { ClickMe }></ClassComponent>
        <NameClassComp></NameClassComp>
        <Example names = {['Python', 'Java', 'C#']}></Example>
        <Example2 names = {['React', 'ReactNative', 'Django']}></Example2>
        <Form></Form>
        */}

        {/*
        
        <MyFragment></MyFragment>

        <MyContext.Provider value = 'This is a value from Context.'>
          <ContextAPI_ComponentA></ContextAPI_ComponentA>
        </MyContext.Provider>
        
        */}
        
        {/*
        
        <Hooks_Counter></Hooks_Counter>
        <Hooks_CounterHooks></Hooks_CounterHooks>
        <FetchData></FetchData>

        */}

        <MyContext.Provider value = 'This is a value from Context.'>
          <ComponentA></ComponentA>
        </MyContext.Provider>
        
        <Reducer></Reducer>
        <FetchDataReducer></FetchDataReducer>

        
      </div>
      
    </>
  )
}

/*

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <a href=''></a>

        <FuncComponent fname = "Bryan" lname = "Pintor"></FuncComponent>
        <ClassComponent uname = "bossing" myclick = { ClickMe }></ClassComponent>

      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )

*/